### ISSUE TITLE
Another code editor for instructors

### ISSUE THREAD

**Issue by y3nr1ng** [liuyenting/judgegirl-core#1]
Do we need another editor interface for instructors? - By @CTinRay 

Before making any decision, can you specify the reason?

**Comment by CTinRay** [comment]
Do you means why I think we need another editor interface?
Because that would be user-friendly, and our project will not be worse than using github as the media of problems. Thus, I think we can just use the editor of github's.

**Comment by y3nr1ng** [comment]
How about a general editor interface for instructors & students, while another add-on to flavored the difference between them, such as broadcasting ability v.s. receiving broadcast? 

Another editor to differentiate two group of people will cause some unwanted couplings effect.

**Comment by CTinRay** [comment]
hmm... I think the editor for programming and for posting an article/problem is difinitly differently.

**Comment by y3nr1ng** [comment]
Uh!?? Online editor and problem set management are already separated, what's your concern..?

**Comment by CTinRay** [comment]
oops... your interface does not mean UI, but between modules?

**Comment by y3nr1ng** [comment]
UI will be separated, and so do the modules.

**Comment by CTinRay** [comment]
ok, actullaly, nothing to be worry.
