### ISSUE TITLE
Site map/structure

### ISSUE THREAD

**Issue by CTinRay** [liuyenting/judgegirl-core#2]
It may be time to discuss the site map/structure?

**Comment by CTinRay** [comment]
In my perspective, our site is composed with some major functions, such as bullet, problems, courses( videos.
Each major function is independent to each other.
And each function has some sub functions, for example problems may contain problem list, score board, ide one.....

I think we can have a navigator bar for major functions.
Every page in our site will have the identical navigator bar.
For sub functions, there is a side column, pages of one major function will have identical side column.

If you guys agree with my perspective, then we can further start to discuss what major functions will contain what sub-functions.

**Comment by y3nr1ng** [comment]
I'd propose using top bar only, no side column. Something like this website: http://thenounproject.com/

**Comment by CTinRay** [comment]
But our functions are much more complex.

**Comment by y3nr1ng** [comment]
Core function
![img_0381](https://cloud.githubusercontent.com/assets/2089799/6426161/5f1a21b0-bf87-11e4-9174-fb273b72de27.jpg)

Core function + 2 Modules
![img_0382](https://cloud.githubusercontent.com/assets/2089799/6426166/8f754d9e-bf87-11e4-850d-f3cedf0b1f71.jpg)

Core function + 1 Module + Showing subfunctions
![img_0383](https://cloud.githubusercontent.com/assets/2089799/6426163/5f4114f0-bf87-11e4-9c11-c8b2886d0466.jpg)

**Comment by y3nr1ng** [comment]
A website that looks "similar" but not entirely the same, http://www.atmel.com/
(regarding the dropdown menu)

**Comment by CTinRay** [comment]
http://www.atmel.com/products/microcontrollers/default.aspx?src=parent
side column may be inevitavle?

**Comment by y3nr1ng** [comment]
Ok.. orz I concur.. If necessary, side column is acceptable, but I really hope we can significantly reduce the need of menus with different orientations.

**Comment by CTinRay** [comment]
If you really hate the side column, maybe we can use drop-down table to replace it?

**Comment by y3nr1ng** [comment]
Probably, there's another reason I'd like to use the top bar as main structure, since it's easier to transform the mobile page to comply google's new design guide. How 'bout Tony?

**Comment by CTinRay** [comment]
see what it response when screen is small.
https://www.meteor.com/projects

If we really want material design, maybe we can give up the navigator bar for mobile devices?

**Comment by CTinRay** [comment]
Anyway, do you guys agree with my proposal to view our site as some major functions, which composed with sub functions?

**Comment by y3nr1ng** [comment]
Interesting, so.. top bar for main functions, such as switching between bulletin board/editor/judger/database, and sidebar for more fine grained, application specific functions such as editor/storage, editor/text editor, editor/interpreter.

**Comment by CTinRay** [comment]
yes, that what I say.

**Comment by yunchih** [comment]
Sidebar can slide in.
Like this:  http://todos.meteor.com/lists/2mZzyBMRhpmxjqnnA
Also, adjust the screen width and see how the app respond. ( so you can simulate how it looks on mobile device. )  You shall see the menu become a single icon.  And the `Make public` and `Delete` icon shrink into just one icon, which is controlled by a line of javascript in list-show.js.

**Comment by CTinRay** [comment]
Ok, for the appearance style, that can be discussed latter.
That is also my view point of modularization.
Let's discuss that in another thread.

**Comment by y3nr1ng** [comment]
So, visual style in another thread, this thread is limited to.. site structure only.
