### ISSUE TITLE
File structure

### ISSUE THREAD

**Issue by CTinRay** [liuyenting/judgegirl-core#4]
After discussing, @liuyenting and I prefer the file structure using root-level directorys.
Please refer to http://docs.meteor.com/#/full/structuringyourapp

> Method 1: Root-Level Folders
> 
> Since the special client, server, and lib directories work if they are anywhere in the path, you can use top-level folders to organize code into modules:
> 
> apples/lib/               # code for apple-related features
> apples/client/
> apples/server/
> 
> oranges/lib/              # code for orange-related features
> oranges/client/
> oranges/server/

For the dependency problem, please @liuyenting do some further explain.
Also can @liuyenting detail how this file structure benifit the version control and update management?

**Comment by y3nr1ng** [comment]
Actually, my original intent for the file structure is:

```
root/
root/mods/

root/mods/DEPENDENCIES.db

root/mods/apples/
root/mods/apples/client/
root/mods/apples/server/
root/mods/apples/lib/

root/mods/oranges/
root/mods/oranges/client/
root/mods/oranges/server/
root/mods/oranges/lib/
```

All the package is managed under mods folder, which means the scanner can implicitly know where to scan the package, and the folder names under the mods folder is directly the installed package, so it's easy to catch-up current mods status.

As for the version controlling and updater script, by replacing the entire folder, and have the main system rescan for module anomalies, module replacement can easily be achieved. And, yup, it also means that we have to abandon the on-the-fly add-on swapping thingy.
